const marveldata = [
    {
        id: 'm1',
        name: 'Spider-Man Venom Short Sleeve T-Shirt',
        category: 'T-Shirts',
        hero: 'spiderman',
        price: 350,
        img1: 'tsvenom1.jpg',
        img2: 'tsvenom2.jpg',
        img3: 'tsvenom3.jpg',
        img4: 'tshirtsize.jpg',
    },
    {
        id: 'm2',
        name: `Iron Man Suit-Up Men's Costume T-Shirt`,
        hero: 'ironman',
        category: 'T-Shirts',
        price: 400,
        img1: 'tsironman1.jpg',
        img2: 'tsironman2.jpg',
        img3: 'tsironman3.jpg',
        img4: 'tshirtsize.jpg',
    },
    {
        id: 'm3',
        name: 'X-Men Distressed Symbol Grey T-Shirt',
        category: 'T-Shirts',
        hero: 'xmen',
        price: 300,
        img1: 'tsxmensymbol1.jpg',
        img2: 'tsxmensymbol2.jpg',
        img3: 'tsxmensymbol3.jpg',
        img4: 'tshirtsize.jpg',
    },
    {
        id: 'm4',
        name: 'Captain America Distressed Shield Navy T-Shirt',
        category: 'T-Shirts',
        hero: 'captainAmerica',
        price: 350,
        img1: 'tscaptain1.jpg',
        img2: 'tscaptain2.jpg',
        img3: 'tscaptain3.jpg',
        img4: 'tshirtsize.jpg',
    },
    {
        id: 'm5',
        name: 'Miles Morales Spider-Man Hat',
        category: 'Hats',
        hero: 'spiderman',
        price: 150,
        img1: 'cspiderman1.jpg',
        img2: 'cspiderman2.jpg',
        img3: 'cspiderman3.jpg',
        img4: 'cspiderman4.jpg',
    },
    {
        id: 'm6',
        name: 'Black Panther Black Camo Fitted Mesh Back Hat',
        category: 'Hats',
        hero: 'blackPanther',
        price: 150,
        img1: 'cblackpanther1.jpg',
        img2: 'cblackpanther2.jpg',
        img3: 'cblackpanther3.jpg',
        img4: 'cblackpanther4.jpg',
    },
    {
        id: 'm7',
        name: 'Punisher Woodland Camo Adjustable Hat',
        category: 'Hats',
        hero: 'punisher',
        price: 150,
        img1: 'cpunisher1.jpg',
        img2: 'cpunisher2.jpg',
        img3: 'cpunisher3.jpg',
        img4: 'cpunisher4.jpg',
    },
    {
        id: 'm8',
        name: 'Marvel Red Label with Comic Scene Sandal Slides',
        category: 'Footwear',
        hero: 'marvel',
        price: 100,
        img1: 'fmarvel1.jpg',
        img2: 'fmarvel2.jpg',
        img3: 'fmarvel3.jpg',
        img4: 'fmarvel4.jpg',
    },
    {
        id: 'm9',
        name: 'Avengers Assemble and Symbol Kids Lighted Canvas Shoes',
        category: 'Footwear',
        hero: 'marvel',
        price: 600,
        img1: 'favengers1.jpg',
        img2: 'favengers2.jpg',
        img3: 'favengers3.jpg',
        img4: 'favengers4.jpg',
    },
    {
        id: 'm10',
        name: 'Doctor Strange Multiverse of Madness Funko Pop! Vinyl Figure',
        category: 'Figures',
        hero: 'doctorStrange',
        price: 100,
        img1: 'fidoctor1.jpg',
        img2: 'fidoctor2.jpg',
    },
    {
        id: 'm11',
        name: 'Marvel Comics The Wolverine Funko Pop! Vinyl Figure',
        category: 'Figures',
        hero: 'wolverine',
        price: 100,
        img1: 'fiwolverine1.jpg',
        img2: 'fiwolverine2.jpg',
    },
]

export default marveldata;