const DcData = [
    {
        id: 'd1',
        name: 'Batman T-Shirt',
        category: 'T-Shirts',
        hero: 'batman',
        price: 350,
        img1: 'tsbatman1.jpg',
        img2: 'tsbatman2.jpg',
        img3: 'tsbatman3.jpg',
        img4: 'tshirtsize.jpg',
    },
    {
        id: 'd11',
        name: 'Flash T-Shirt',
        category: 'T-Shirts',
        hero: 'flash',
        price: 350,
        img1: 'tsflash1.jpg',
        img2: 'tsflash2.jpg',
        img3: 'tsflash3.jpg',
        img4: 'tshirtsize.jpg',
    },
    {
        id: 'd12',
        name: 'Wonder Woman Costume T-Shirt',
        category: 'T-Shirts',
        hero: 'wonderwoman',
        price: 350,
        img1: 'tsww1.jpg',
        img2: 'tsww2.jpg',
        img3: 'tsww3.jpg',
        img4: 'tsww4.jpg',
    },
    {
        id: 'd2',
        name: 'Batman Hat/Cap',
        category: 'Hats',
        hero: 'batman',
        price: 350,
        img1: 'hbatman1.jpg',
        img2: 'hbatman2.jpg',
        img3: 'hbatman3.jpg',
        img4: 'hbatman4.jpg',
    },
    {
        id: 'd3',
        name: 'Batman Hat/Cap',
        category: 'Hats',
        hero: 'batman',
        price: 350,
        img1: 'h2batman1.jpg',
        img2: 'h2batman2.jpg',
        img3: 'h2batman3.jpg',
        img4: 'h2batman4.jpg',
    },
    {
        id: 'd4',
        name: 'Superman Hoodie',
        category: 'Hoodies',
        hero: 'superman',
        price: 350,
        img1: 'hosuperman1.jpg',
        img2: 'hosuperman2.jpg',
    },
    {
        id: 'd5',
        name: 'Flash Hat/Cap',
        category: 'Hats',
        hero: 'flash',
        price: 350,
        img1: 'hflash1.jpg',
        img2: 'hflash2.jpg',
        img3: 'hflash3.jpg',
        img4: 'hflash4.jpg',
    },
    {
        id: 'd6',
        name: 'Superman socks',
        category: 'Socks',
        hero: 'superman',
        price: 350,
        img1: 'ssuperman1.jpg',
        img2: 'ssuperman2.jpg',
    },
    {
        id: 'd7',
        name: 'Superman socks',
        category: 'Socks',
        hero: 'superman',
        price: 350,
        img1: 's2superman1.jpg',
        img2: 's2superman2.jpg',
    },
    {
        id: 'd8',
        name: 'Flash socks',
        category: 'Socks',
        hero: 'flash',
        price: 350,
        img1: 'sflash1.jpg',
    },
    {
        id: 'd9',
        name: 'Batman socks',
        category: 'Socks',
        hero: 'batman',
        price: 350,
        img1: 'sbatman1.jpg',
        img2: 'sbatman2.jpg',
    },
    {
        id: 'd10',
        name: 'Wonder Woman socks',
        category: 'Socks',
        hero: 'wonderwoman',
        price: 100,
        img1: 'sww1.jpg',
        img2: 'sww2.jpg',
    },
    
]

export default DcData;